### ISSUE TITLE
Default export of the module has or is using private name

### ISSUE THREAD

**Issue by webdevnerdstuff** [qmhc/vite-plugin-dts#241]
### Describe the bug

When running my `pnpm build` script I'm getting a new error since updating `vite-plugin-dts` to v3 and up. In turn it's preventing the `VDrilldownTable.vue.ts` file getting generated.

### Reproduction

https://github.com/webdevnerdstuff/vuetify-drilldown-table/tree/vue-plugin-dts

### Steps to reproduce

1. Clone the repo
2. `pnpm i`
3. `pnpm build`
4. Notice the error in the terminal

Output of `pnpm build`

```
vite v4.4.3 building for production...
src/plugin/VDrilldownTable.vue.ts(1033,1): error TS4082: Default export of the module has or is using private name 'DataTableItem'.
src/plugin/VDrilldownTable.vue.ts(1033,1): error TS4082: Default export of the module has or is using private name 'DataTableItem'.
```

FWIW:  The`DataTableItem` type is used in the code, but even if I replaced it with another name, it still gives me the same error. It is a type defined by Vuetify (that I don't import). Either way, I've never had this error before.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.31 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.0.1 - ~/.nvm/versions/node/v19.0.1/bin/node
    Yarn: 1.22.19 - ~/node_modules/.bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v19.0.1/bin/npm
    pnpm: 8.6.7 - ~/.nvm/versions/node/v19.0.1/bin/pnpm
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3
    vite: ^4.3.9 => 4.4.3
    vite-plugin-dts: ^3.2.0 => 3.2.0
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
This error is due to incorrect usage of type definition. In your case, the origin is (`src/types/index.ts`):

![image](https://github.com/qmhc/vite-plugin-dts/assets/40221744/6cb273b7-29e9-47b3-97e6-4bbc08958413)

`VDataTableRow` is defined by `const`:

![image](https://github.com/qmhc/vite-plugin-dts/assets/40221744/b903386c-8973-4357-abbf-33c437510de8)

So you should use `typeof VDataTableRow` not directly `DataTableRow`:

![image](https://github.com/qmhc/vite-plugin-dts/assets/40221744/507e9907-7fbf-4a40-bb50-b3eed0a5e4dd)

**Comment by webdevnerdstuff** [comment]
@qmhc Thank you for the quick response! I changed it to that and the error does go away. 

What I don't understand is that `VDataTable` and `VSkeletonLoader` are also using `declare const` with similar structure, yet none of those props needed `typeof`. Am I just missing some typescript knowledge (which is possible) as to why `VDataTableRow` causes the build errors (but code works as intended), and the others doing something similar do not? If it's too much to explain, if you could point me in the right direction to understand it better that would be appreciated.

I also assume the older version v2 didn't check for this, but does now in v3?
