### PR TITLE
chore: update ts-morph@17.0.1

### PR DESCRIPTION
**Pull request by ekaradon**
I just want to be able to use the new keyword `satisfies` which should be working with `ts-morph` @17.0.1 if that's okay with you? Not sure if anything else is required here?

### CODE REVIEW

**Comment by justinhelmer** [comment]
We are currently using a fork of this repo until we are able to get this PR merged and published.

Thanks @ekaradon for moving the needle!

**Review by qmhc — APPROVED** [review]

**Comment by sybrendotinga** [comment]
Any updates on this being released? I currently have a scenario where my code could benefit from using `satisfies` 😄 

But I get the following errors: 

```
[vite:dts] Start generate declaration files...
lib/composables/defineNotification.ts:21:5 - error TS1005: ',' expected.

21   } satisfies Notification
       ~~~~~~~~~
lib/composables/defineNotification.ts:21:5 - error TS7005: Variable 'satisfies' implicitly has an 'any' type.

```

**Comment by justinhelmer** [comment]
L:ooks like we got it merged!

Just need a release now... 🤞

**Comment by sybrendotinga** [comment]
@qmhc could you please take a look if this can be released 😄
