### ISSUE TITLE
After 2.1.X update i get TS2307: Cannot find module ... error on all my .vue files

### ISSUE THREAD

**Issue by auirarrazaval** [qmhc/vite-plugin-dts#384]
### Describe the bug

It took me a while to narrow this down from the project, but eventually I came to realize that this library's update is what triggered the errors. I'm guessing that it's related to the vue language server, but no sure what exactly.

In general terms, when updating to v2.1.X a TS2307 error starts showing up for every vue file. I have provided a minimum reproduction, which is basically my project trimmed

### Reproduction

https://github.com/auirarrazaval/vite-plugin-dts-build-error-repr

### Steps to reproduce

```
git clone ...
# In case not enabled, to use yarn4
corepack enable
yarn
yarn install
yarn sdks
yarn build
```
Notice that the build goes through. Also note that the `vue-tsc` command runs with no issues, but the tsc error shows up when building
![image](https://github.com/user-attachments/assets/0b8b850f-2690-4924-a7f6-2b5bc665f108)

If you downgrade vite-plugin-dts to @4.0.3, the error doesn't show up:
![image](https://github.com/user-attachments/assets/a4aaafa9-cbd5-4a93-a379-0698d0b917ad)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 9 5900HS with Radeon Graphics
    Memory: 2.25 GB / 7.76 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.16.0 - /tmp/xfs-47c61424/node
    Yarn: 4.4.1 - /tmp/xfs-47c61424/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm

libraries should be the versions sin the package.json, as I updated it
```

### Validations

- [X] Read the [FAQ](https://github.com/qmhc/vite-plugin-dts#faq).
- [X] Check that there isn't [already an issue](https://github.com/qmhc/vite-plugin-dts/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qmhc** [comment]
It seems to only be occurred with `yarm@4` ...

**Comment by auirarrazaval** [comment]
@qmhc Just want to confirm that 4.2.2 solved the issue. Thank you for your help!
