### ISSUE TITLE
Error: Cannot find module 'debug' in new release.

### ISSUE THREAD

**Issue by Leon2ev** [qmhc/vite-plugin-dts#64]
Yesterday been working with version 1.0.2 and everything went fine. 

Today with the same setup updated to version 1.0.3 and got an error from below.
> error during build:
Error: Cannot find module 'debug'

**Comment by qmhc** [comment]
A missing when rollback the `package.json`, is fixed in 1.0.4 😭
